name: Node.js NPM Package

on: workflow_dispatch # 직접 workflow 실행시.  https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
    public-npm:
        # needs: build   # jobs.build 가 선행되어야 할 때.
        runs-on: ubuntu-latest
        steps:
            # 해당 저장소 코드 가져오기
            - name: Checkout
              uses: actions/checkout@v2

            # Node 설치
            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
                  # https://blog.outsider.ne.kr/1559
                  registry-url: 'https://registry.npmjs.org/'

            # 라이브러리 설치.
            - name: Install dependencies
              run: npm ci

            # 빌드
            - name: Build
              run: npm run build --if-present

            # 테스트 수행.
            - name: Run tests
              run: yarn test

            # NPM
            - name: NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
